language: c
os:
  - osx
before_install: |
  brew update
  brew tap manastech/crystal
install: |
  brew install gmp libevent crystal
  curl "http://crystal-lang.s3.amazonaws.com/llvm/llvm-3.5.0-1-darwin-x86_64.tar.gz" | tar xz -C /tmp
  export LIBRARY_PATH=/usr/local/opt/crystal/embedded/lib
  export PATH=/tmp/llvm-3.5.0-1/bin:$PATH
  export CRYSTAL_CONFIG_VERSION=ci
script:
  - make
  - bin/crystal spec/std/process/run_spec.cr
notifications:
  email: false
