language: c
os:
  - osx
  - linux
before_install: |
  case $TRAVIS_OS_NAME in
    linux)
      curl http://dist.crystal-lang.org/apt/setup.sh | sudo bash
      sudo apt-get -q update
      ;;

    osx)
      brew update
      brew tap manastech/crystal
      ;;
  esac
install: |
  case $TRAVIS_OS_NAME in
    linux)
      sudo apt-get install libgmp3-dev crystal
      sudo sed -i -e 's/.*LIBRARY_PATH.*/export LIBRARY_PATH=\"$INSTALL_DIR\/embedded\/lib${LIBRARY_PATH:\+:$LIBRARY_PATH}\"/' /opt/crystal/bin/crystal
      curl "http://crystal-lang.s3.amazonaws.com/llvm/llvm-3.5.0-1-linux-x86_64.tar.gz" | tar xz -C /tmp
      curl "http://crystal-lang.s3.amazonaws.com/pcl/libpcl-1.12-1-linux-x86_64.tar.gz" | tar xz -C /tmp
      export LIBRARY_PATH=/opt/crystal/embedded/lib:/tmp/libpcl-1.12-1/lib
      ;;

    osx)
      brew install gmp libevent crystal
      curl "http://crystal-lang.s3.amazonaws.com/llvm/llvm-3.5.0-1-darwin-x86_64.tar.gz" | tar xz -C /tmp
      export LIBRARY_PATH=/usr/local/opt/crystal/embedded/lib
      ;;
  esac
  export PATH=/tmp/llvm-3.5.0-1/bin:$PATH
  export CRYSTAL_CONFIG_VERSION=ci
script:
  - make
  - bin/crystal spec/std/process/run_spec.cr
notifications:
  email: false
